### ISSUE TITLE
Support for Winter 1.2 (Laravel 9)?

### ISSUE THREAD

**Issue by tintong** [zaxbux/oc-gmaildriver-plugin#13]
Hello,

I've been using your plugin to send emails from my winter cms but since upgrading to Winter 1.2, which uses Laravel 9, this plugin has stopped working.

I've asked Winter for support who ask me to contact you.

The error I am getting is:

Expected response code "250/251/252" but got code "550", with message "550 5.7.1 Relaying denied".

Any support would be really apreciated.

Thank you.

**Comment by zaxbux** [comment]
That sounds like an SMTP error. Can you confirm that your email settings are configured for the Gmail plugin?

**Comment by tintong** [comment]
Hello,

It was working fine before the upgrade and then it stopped.
Winter 1.2 uses Laravel 9, which has a different email bit in the code.

Thanks

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by tintong** [comment]
Hello,

I switched from Gmail to O365 for emailing and my original issue has been fixed.
I was told that this plugin would benefit people if it could still be updated to reflect Laravel's version 9 email changes please.

Thanks

**Comment by zaxbux** [comment]
Version 1.1.0 of this plugin is now available and supports Winter CMS 1.2.
