### ISSUE TITLE
Make scopes a config option

### ISSUE THREAD

**Issue by alxy** [zaxbux/oc-gmaildriver-plugin#2]
Hi, thanks for this awesome plugin.

Can you make the [scopes](https://github.com/zaxbux/oc-gmaildriver-plugin/blob/master/classes/GoogleAPI.php#L38) a (file-based) [configuration option](https://octobercms.com/docs/plugin/settings#file-configuration)? I want to use your plugin not only to send mails, but also to read and delete mails and dont want to bother with the authentication stuff, that is really very nicely integrated here already :)

**Comment by zaxbux** [comment]
Yes! This should be really simple to implement. Sorry for the huge delay, apparently I wasn't watching this repo.

**Comment by zaxbux** [comment]
Added this capability with commit 37282a1ac7004b1adb8e769626dedfda22b275b8. Will be pushed to the marketplace soon.

Thanks for the suggestion and finding the plugin useful!
