### ISSUE TITLE
Quick question about benefits

### ISSUE THREAD

**Issue by roojai** [zaxbux/oc-gmaildriver-plugin#4]
Thanks for this plugin - just got it set up.

I was wondering what the benefit was to using this over normal SMTP. Am I right in thinking that I still need to "allow less secure apps" on the mailing account for this to work?

**Comment by zaxbux** [comment]
The `Allow Less Secure Apps` settings may not be available to users with 2FA enabled or to GSuite accounts where the administrator has disabled `Less Secure Apps`. Apps accessing Google services should use a modern and secure access method like OAuth.

Additional plugin capabilities may be added in the future, which might require use of the Google APIs.

For GSuite customers, LSAs will no longer work after Feb 15, 2021: [Google's announcement](https://gsuiteupdates.googleblog.com/2019/12/less-secure-apps-oauth-google-username-password-incorrect.html)
