### ISSUE TITLE
Can't authorize plugin app

### ISSUE THREAD

**Issue by queengab** [zaxbux/oc-gmaildriver-plugin#8]
Hi,

i'm trying to use your plugin on latest Winter release 1.1.7
I followed the api credenztials instruction, installed the plugin and cofigured it.

<img width="801" alt="image" src="https://user-images.githubusercontent.com/9084695/143418391-c1c6f0c5-a173-4c02-99b8-b6846f860973.png">
If i click on the authorize button nothing happens.

If i go to redirect URI i encounter this problem:
<img width="588" alt="image" src="https://user-images.githubusercontent.com/9084695/143418961-a7189338-d2b5-46df-aee8-61a41731c35f.png">

Please can you help me?

Thanks!

I think this plugin is very usefull. I wanted also to crfeate something like this.
Have you ever thinked about using gmail as mail sander also for mailing list? Extendind this plugin also to send mass mail.
Gmail can send 2000 mail per day from api, if i remember well!

**Comment by queengab** [comment]
Hi pardon me,

find the trick!
I didn't realize that `composer require zaxbux/wn-gmaildriver-plugin` downloaded the 1.0.13 version!

With 1.0.15 no problem and all goes well with Winter!
Bye

**Comment by zaxbux** [comment]
Glad it is working for you! I'll update the README to be a bit more clear.

P.S. You can send mail through the Gmail driver using any Winter CMS plugin ([docs](https://wintercms.com/docs/services/mail#sending-mail)), a mailing list plugin is certainly a possibility (although I'll have to leave that project to someone with more time than me 😅).
